<?php

return [
    'topics' => [
        [
            'id' => 'ai-machine-learning',
            'category' => 'Technology',
            'name' => 'AI & Machine Learning',
            'brief' => 'Track meaningful advances in AI models, products, research, safety, and real-world adoption. Prefer primary research and product documentation, independent evaluation, and clear distinctions between demonstrated capability and marketing claims.',
            'keywords' => ['artificial intelligence', 'models', 'agents', 'automation'],
        ],
        [
            'id' => 'cybersecurity-privacy',
            'category' => 'Technology',
            'name' => 'Cybersecurity & Privacy',
            'brief' => 'Cover important vulnerabilities, breaches, defensive practices, privacy policy, and security research. Prioritize original advisories and affected vendors, explain practical impact, and avoid amplifying unverified threat claims.',
            'keywords' => ['security', 'breaches', 'vulnerabilities', 'data protection'],
        ],
        [
            'id' => 'software-open-source',
            'category' => 'Technology',
            'name' => 'Software Engineering & Open Source',
            'brief' => 'Follow consequential releases, developer tools, open-source projects, engineering practices, and ecosystem changes. Favor release notes, repositories, maintainers, benchmarks, and technically credible independent analysis.',
            'keywords' => ['programming', 'developer tools', 'repositories', 'cloud'],
        ],
        [
            'id' => 'consumer-technology',
            'category' => 'Technology',
            'name' => 'Consumer Technology',
            'brief' => 'Track notable devices, apps, platforms, and digital services with attention to usefulness, price, availability, privacy, repairability, and credible hands-on assessment rather than launch-day hype.',
            'keywords' => ['gadgets', 'phones', 'apps', 'reviews'],
        ],
        [
            'id' => 'space-astronomy',
            'category' => 'Science & Health',
            'name' => 'Space & Astronomy',
            'brief' => 'Cover major missions, discoveries, launches, observatories, and space policy. Prefer space agencies, mission teams, peer-reviewed research, and informed context about uncertainty and scientific significance.',
            'keywords' => ['nasa', 'esa', 'rockets', 'cosmos'],
        ],
        [
            'id' => 'climate-environment',
            'category' => 'Science & Health',
            'name' => 'Climate & Environment',
            'brief' => 'Follow climate science, extreme-weather attribution, conservation, pollution, and environmental policy. Use current scientific and official evidence, include geographic context, and distinguish projections from observed outcomes.',
            'keywords' => ['weather', 'conservation', 'pollution', 'ecology'],
        ],
        [
            'id' => 'health-medicine',
            'category' => 'Science & Health',
            'name' => 'Health & Medicine',
            'brief' => 'Track important clinical research, public-health developments, treatments, and healthcare policy. Prioritize authoritative and peer-reviewed evidence, explain study limitations, and avoid presenting preliminary findings as medical advice.',
            'keywords' => ['clinical trials', 'public health', 'treatments', 'healthcare'],
        ],
        [
            'id' => 'biology-genetics',
            'category' => 'Science & Health',
            'name' => 'Biology & Genetics',
            'brief' => 'Cover significant discoveries in biology, genetics, evolution, and biotechnology. Prefer original research and expert interpretation, with clear treatment of experimental limits, ethics, and possible applications.',
            'keywords' => ['genomics', 'biotech', 'evolution', 'life sciences'],
        ],
        [
            'id' => 'startups-venture-capital',
            'category' => 'Business & Finance',
            'name' => 'Startups & Venture Capital',
            'brief' => 'Follow notable startups, funding, acquisitions, shutdowns, and shifts in venture markets. Look beyond announcements to product evidence, business fundamentals, investor context, and independent reporting.',
            'keywords' => ['founders', 'funding', 'venture', 'entrepreneurship'],
        ],
        [
            'id' => 'markets-economy',
            'category' => 'Business & Finance',
            'name' => 'Markets & Economy',
            'brief' => 'Track major economic indicators, central-bank decisions, market-moving events, and structural trends. Prefer official data and primary statements, distinguish reporting from analysis, and explain uncertainty without investment hype.',
            'keywords' => ['stocks', 'macroeconomics', 'central banks', 'inflation'],
        ],
        [
            'id' => 'personal-finance',
            'category' => 'Business & Finance',
            'name' => 'Personal Finance',
            'brief' => 'Cover practical developments affecting saving, borrowing, taxes, insurance, retirement, and household costs. Emphasize current rules, transparent tradeoffs, reputable sources, and broadly applicable education rather than individualized advice.',
            'keywords' => ['money', 'saving', 'tax', 'retirement'],
        ],
        [
            'id' => 'careers-future-work',
            'category' => 'Business & Finance',
            'name' => 'Careers & Future of Work',
            'brief' => 'Follow workplace trends, labor markets, skills, management, remote work, and automation. Prefer evidence over executive anecdotes and include practical implications for workers and employers.',
            'keywords' => ['jobs', 'workplace', 'remote work', 'skills'],
        ],
        [
            'id' => 'global-affairs',
            'category' => 'Public Affairs',
            'name' => 'Global Affairs',
            'brief' => 'Track consequential international events, diplomacy, conflict, trade, and regional change. Use multiple credible perspectives, prioritize direct records where available, and clearly label disputed claims and uncertainty.',
            'keywords' => ['world news', 'geopolitics', 'diplomacy', 'international'],
        ],
        [
            'id' => 'public-policy-regulation',
            'category' => 'Public Affairs',
            'name' => 'Public Policy & Regulation',
            'brief' => 'Cover laws, regulations, court decisions, and public programs that materially affect people or industries. Prefer official text and records, explain implementation and likely impact, and include credible criticism.',
            'keywords' => ['government', 'law', 'courts', 'regulation'],
        ],
        [
            'id' => 'local-government-civic-life',
            'category' => 'Public Affairs',
            'name' => 'Local Government & Civic Life',
            'brief' => 'Follow decisions, services, elections, infrastructure, and community issues in the user’s area. Prioritize specific local sources, official records, dates, locations, and practical consequences for residents.',
            'keywords' => ['city', 'county', 'municipal', 'community'],
        ],
        [
            'id' => 'education-learning',
            'category' => 'Public Affairs',
            'name' => 'Education & Learning',
            'brief' => 'Track education policy, schools, universities, learning research, and useful learning resources. Balance institutional announcements with evidence, educator and student perspectives, and concrete outcomes.',
            'keywords' => ['schools', 'universities', 'teaching', 'courses'],
        ],
        [
            'id' => 'film-television',
            'category' => 'Culture & Entertainment',
            'name' => 'Film & Television',
            'brief' => 'Follow notable releases, productions, festivals, criticism, and industry shifts. Mix timely news with thoughtful reviews and interviews, clearly distinguish opinion, and avoid unnecessary spoilers.',
            'keywords' => ['movies', 'streaming', 'cinema', 'series'],
        ],
        [
            'id' => 'music',
            'category' => 'Culture & Entertainment',
            'name' => 'Music',
            'brief' => 'Cover meaningful releases, performances, tours, artist interviews, criticism, and industry change. Seek genre and geographic variety, original sources, and informed commentary rather than celebrity gossip.',
            'keywords' => ['albums', 'artists', 'concerts', 'songs'],
        ],
        [
            'id' => 'books-publishing',
            'category' => 'Culture & Entertainment',
            'name' => 'Books & Publishing',
            'brief' => 'Track notable books, authors, reviews, awards, publishing trends, and literary events. Include varied genres and voices, favor substantive criticism, and distinguish recommendations from reported news.',
            'keywords' => ['literature', 'authors', 'reading', 'reviews'],
        ],
        [
            'id' => 'video-games',
            'category' => 'Culture & Entertainment',
            'name' => 'Video Games',
            'brief' => 'Follow significant games, updates, studios, platforms, criticism, and industry developments. Prefer hands-on reporting, developer sources, and player-relevant detail while avoiding rumor amplification.',
            'keywords' => ['gaming', 'consoles', 'pc games', 'studios'],
        ],
        [
            'id' => 'art-museums',
            'category' => 'Culture & Entertainment',
            'name' => 'Art & Museums',
            'brief' => 'Cover exhibitions, artists, museums, public art, criticism, and cultural heritage. Highlight varied regions and traditions, use authoritative event details, and include images only with clear rights and attribution.',
            'keywords' => ['galleries', 'exhibitions', 'artists', 'heritage'],
        ],
        [
            'id' => 'history-archaeology',
            'category' => 'Culture & Entertainment',
            'name' => 'History & Archaeology',
            'brief' => 'Follow important discoveries, new scholarship, preservation, and public-history projects. Prefer researchers, institutions, and peer-reviewed evidence, and avoid sensational claims unsupported by the record.',
            'keywords' => ['ancient history', 'discoveries', 'heritage', 'archives'],
        ],
        [
            'id' => 'football',
            'category' => 'Sports',
            'name' => 'Football',
            'brief' => 'Track important matches, competitions, transfers, tactics, and governance across the leagues and teams relevant to the user. Prioritize confirmed team or competition information and insightful match analysis over rumor.',
            'keywords' => ['soccer', 'premier league', 'champions league', 'fifa'],
        ],
        [
            'id' => 'basketball',
            'category' => 'Sports',
            'name' => 'Basketball',
            'brief' => 'Cover major games, leagues, players, tactics, transactions, and competition news. Balance official updates, reliable reporting, statistics, and informed analysis.',
            'keywords' => ['nba', 'wnba', 'college basketball', 'fiba'],
        ],
        [
            'id' => 'motorsport',
            'category' => 'Sports',
            'name' => 'Motorsport',
            'brief' => 'Follow significant races, teams, drivers, engineering, regulations, and championship developments. Prefer official timing, steward decisions, team sources, and technically informed independent analysis.',
            'keywords' => ['formula 1', 'racing', 'motogp', 'rally'],
        ],
        [
            'id' => 'athletics-major-events',
            'category' => 'Sports',
            'name' => 'Athletics & Major Events',
            'brief' => 'Track notable athletics results, championships, Olympic and Paralympic sport, records, and athlete stories. Use official results and schedules, include global variety, and distinguish confirmed findings from allegations.',
            'keywords' => ['olympics', 'track and field', 'marathons', 'championships'],
        ],
        [
            'id' => 'travel',
            'category' => 'Lifestyle & Hobbies',
            'name' => 'Travel',
            'brief' => 'Find useful destination reporting, transport changes, itineraries, cultural context, and timely travel developments. Verify current opening, visa, safety, and pricing information and favor locally informed sources.',
            'keywords' => ['destinations', 'flights', 'hotels', 'tourism'],
        ],
        [
            'id' => 'food-cooking',
            'category' => 'Lifestyle & Hobbies',
            'name' => 'Food & Cooking',
            'brief' => 'Cover compelling recipes, techniques, restaurants, ingredients, food culture, and industry developments. Prefer tested guidance, credible culinary voices, geographic variety, and practical detail.',
            'keywords' => ['recipes', 'restaurants', 'chefs', 'cuisine'],
        ],
        [
            'id' => 'fitness-wellness',
            'category' => 'Lifestyle & Hobbies',
            'name' => 'Fitness & Wellness',
            'brief' => 'Track useful exercise, recovery, sleep, and wellbeing research and practices. Favor qualified sources and strong evidence, explain limitations, and avoid miracle claims or individualized medical advice.',
            'keywords' => ['exercise', 'training', 'sleep', 'wellbeing'],
        ],
        [
            'id' => 'photography',
            'category' => 'Lifestyle & Hobbies',
            'name' => 'Photography',
            'brief' => 'Follow photography projects, techniques, exhibitions, cameras, editing tools, and visual storytelling. Prioritize strong examples, practitioner insight, and useful creative or technical takeaways.',
            'keywords' => ['cameras', 'photo editing', 'photographers', 'visual art'],
        ],
        [
            'id' => 'gardening',
            'category' => 'Lifestyle & Hobbies',
            'name' => 'Gardening',
            'brief' => 'Find seasonal, climate-appropriate guidance on plants, gardens, soil, wildlife, and sustainable growing. Prefer horticultural institutions, experienced practitioners, and advice tied to place and season.',
            'keywords' => ['plants', 'horticulture', 'vegetable garden', 'landscaping'],
        ],
        [
            'id' => 'diy-home-improvement',
            'category' => 'Lifestyle & Hobbies',
            'name' => 'DIY & Home Improvement',
            'brief' => 'Surface practical projects, repair guidance, tools, materials, and home-design ideas. Favor clear instructions and credible expertise, call out safety considerations, and avoid disguised product promotion.',
            'keywords' => ['repairs', 'woodworking', 'tools', 'renovation'],
        ],
        [
            'id' => 'fashion-design',
            'category' => 'Lifestyle & Hobbies',
            'name' => 'Fashion & Design',
            'brief' => 'Cover notable collections, designers, materials, craftsmanship, visual culture, and industry change. Seek global and independent perspectives and distinguish criticism from promotional coverage.',
            'keywords' => ['style', 'designers', 'textiles', 'runways'],
        ],
        [
            'id' => 'parenting-family',
            'category' => 'Lifestyle & Hobbies',
            'name' => 'Parenting & Family',
            'brief' => 'Find practical, evidence-aware coverage of family life, child development, education, activities, and policy. Prefer qualified sources, acknowledge varied circumstances, and avoid prescriptive or alarmist framing.',
            'keywords' => ['children', 'families', 'child development', 'activities'],
        ],
        [
            'id' => 'local-events',
            'category' => 'Community & Sustainability',
            'name' => 'Local Events',
            'brief' => 'Find worthwhile upcoming events near the user, including arts, music, sport, markets, talks, and community gatherings. Verify the organizer, venue, date, location, availability, and official event link.',
            'keywords' => ['what is on', 'festivals', 'events calendar', 'near me'],
        ],
        [
            'id' => 'clean-energy-sustainability',
            'category' => 'Community & Sustainability',
            'name' => 'Clean Energy & Sustainability',
            'brief' => 'Track credible advances in energy, transport, buildings, materials, and circular systems. Prefer measurable deployments, original data, and independent evaluation over corporate sustainability claims.',
            'keywords' => ['renewables', 'solar', 'batteries', 'circular economy'],
        ],
    ],
    'directives' => [
        [
            'id' => 'prefer-primary-sources',
            'category' => 'Source Quality',
            'label' => 'Prefer original sources',
            'body' => 'Prefer primary sources, original research, official records, and first-party documentation when they are available.',
            'strength' => 'soft',
            'keywords' => ['official', 'research', 'documentation'],
        ],
        [
            'id' => 'corroborate-high-impact-claims',
            'category' => 'Source Quality',
            'label' => 'Corroborate important claims',
            'body' => 'Require independent corroboration for disputed, surprising, consequential, or fast-moving claims before publishing them.',
            'strength' => 'hard',
            'keywords' => ['verification', 'multiple sources', 'fact checking'],
        ],
        [
            'id' => 'avoid-low-quality-aggregators',
            'category' => 'Source Quality',
            'label' => 'Avoid weak aggregators',
            'body' => 'Avoid low-quality aggregators, content farms, copied reporting, and sources that do not provide meaningful original evidence.',
            'strength' => 'hard',
            'keywords' => ['spam', 'seo', 'copied content'],
        ],
        [
            'id' => 'prefer-accessible-sources',
            'category' => 'Accessibility',
            'label' => 'Prefer accessible sources',
            'body' => 'Prefer sources that users can open without a subscription, login, or intrusive access barrier when equally credible coverage exists.',
            'strength' => 'soft',
            'keywords' => ['paywall', 'free', 'login'],
        ],
        [
            'id' => 'prefer-clear-explanations',
            'category' => 'Accessibility',
            'label' => 'Favor clear explanations',
            'body' => 'Favor sources and summaries that explain specialist ideas clearly without oversimplifying important uncertainty or tradeoffs.',
            'strength' => 'soft',
            'keywords' => ['plain language', 'explainers', 'clarity'],
        ],
        [
            'id' => 'include-local-perspectives',
            'category' => 'Diversity',
            'label' => 'Include local perspectives',
            'body' => 'Include credible local or regional sources and perspectives when a story affects a specific place or community.',
            'strength' => 'soft',
            'keywords' => ['regional', 'community', 'geography'],
        ],
        [
            'id' => 'vary-geographic-coverage',
            'category' => 'Diversity',
            'label' => 'Vary geographic coverage',
            'body' => 'Seek geographic variety and avoid allowing one country or media market to dominate the feed unless the topic requires it.',
            'strength' => 'soft',
            'keywords' => ['global', 'international', 'regions'],
        ],
        [
            'id' => 'include-criticism-viewpoints',
            'category' => 'Diversity',
            'label' => 'Include criticism and alternatives',
            'body' => 'Include credible criticism, competing interpretations, or meaningful alternatives when a story involves contested choices.',
            'strength' => 'soft',
            'keywords' => ['viewpoints', 'debate', 'alternatives'],
        ],
        [
            'id' => 'prioritize-recent-developments',
            'category' => 'Freshness',
            'label' => 'Prioritize recent developments',
            'body' => 'Prioritize genuinely new developments and verify publication and event dates before treating a story as current.',
            'strength' => 'soft',
            'keywords' => ['timely', 'latest', 'dates'],
        ],
        [
            'id' => 'include-follow-ups',
            'category' => 'Freshness',
            'label' => 'Include meaningful follow-ups',
            'body' => 'Look for follow-ups that show what happened after an announcement, promise, launch, ruling, or major event.',
            'strength' => 'soft',
            'keywords' => ['outcomes', 'updates', 'accountability'],
        ],
        [
            'id' => 'balance-breaking-evergreen',
            'category' => 'Freshness',
            'label' => 'Balance news and evergreen value',
            'body' => 'Balance timely developments with durable explainers or analysis that will remain useful after the immediate news cycle.',
            'strength' => 'soft',
            'keywords' => ['context', 'evergreen', 'breaking news'],
        ],
        [
            'id' => 'prefer-concise-explainers',
            'category' => 'Depth & Format',
            'label' => 'Prefer concise explainers',
            'body' => 'Prefer concise, information-dense coverage that quickly explains what happened, why it matters, and what remains uncertain.',
            'strength' => 'soft',
            'keywords' => ['short', 'summary', 'efficient'],
        ],
        [
            'id' => 'prefer-deep-analysis',
            'category' => 'Depth & Format',
            'label' => 'Include deeper analysis',
            'body' => 'Include substantive analysis and background for complex stories instead of limiting the feed to short announcements.',
            'strength' => 'soft',
            'keywords' => ['long reads', 'background', 'detail'],
        ],
        [
            'id' => 'include-practical-takeaways',
            'category' => 'Depth & Format',
            'label' => 'Include practical takeaways',
            'body' => 'When appropriate, explain the concrete implications, decisions, opportunities, or next steps that matter to the reader.',
            'strength' => 'soft',
            'keywords' => ['actionable', 'useful', 'implications'],
        ],
        [
            'id' => 'distinguish-fact-opinion',
            'category' => 'Editorial Quality',
            'label' => 'Separate fact from opinion',
            'body' => 'Clearly distinguish verified facts, publisher claims, estimates, analysis, and opinion in every story.',
            'strength' => 'hard',
            'keywords' => ['claims', 'analysis', 'evidence'],
        ],
        [
            'id' => 'state-uncertainty',
            'category' => 'Editorial Quality',
            'label' => 'State uncertainty',
            'body' => 'State material uncertainty, limitations, disputes, and missing evidence instead of presenting an unresolved claim as settled.',
            'strength' => 'hard',
            'keywords' => ['limitations', 'confidence', 'unknowns'],
        ],
        [
            'id' => 'avoid-repetitive-announcements',
            'category' => 'Editorial Quality',
            'label' => 'Avoid repetitive announcements',
            'body' => 'Avoid filling the feed with repetitive press releases, near-duplicate coverage, or minor updates that add no meaningful information.',
            'strength' => 'hard',
            'keywords' => ['duplicates', 'press releases', 'repetition'],
        ],
        [
            'id' => 'avoid-sensational-framing',
            'category' => 'Editorial Quality',
            'label' => 'Avoid sensational framing',
            'body' => 'Avoid clickbait, sensational framing, celebrity gossip, and emotionally charged claims that are not supported by the evidence.',
            'strength' => 'hard',
            'keywords' => ['clickbait', 'hype', 'gossip'],
        ],
    ],
];
